services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/traefik"
      - "--providers.file.watch=true"
      - "--serversTransport.insecureSkipVerify=true"
    labels:
      # global redirect to https
      - "traefik.enable=true"
      - "traefik.frontend.rule=HostRegexp(`{any:.+}`)"
      - "traefik.port=80"
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/traefik"
    ports:
      - "80:80"
      - "443:443"

  mattermost:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.routers.mattermost.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
    ports:
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp